config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'gallery' => 'welcome#gallery'
  get 'order_completed' => 'welcome#order_completed'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}

  resources :products
  resources :variants
  resources :carts do
    member do
      post :add_to_cart
      put :update_cart
      delete :delete_cart_item
      post :place_order
    end
  end

  resources :billings

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @product_variants = Variant.all.limit(6)

    p @product_variants
  end

  def about

  end

  def contact

  end

  def order_completed

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<!-- banner -->
<div class="banner-slider">
  <div class="banner-pos">
    <div class="banner one page-head">
      <div class="container">
        <div class="navigation text-center">
          <span class="menu"><img src="/assets/menu.png" alt=""/></span>
          <ul class="nav1">
            <li><a href="/">HOME</a></li>
            <li><a class="active" href="/about">ABOUT</a></li>
            <li><a href="/products">OUR MENU</a></li>
            <li><a href="/gallery">GALLERY</a></li>
            <!--<li><a href="typography.html">TODAY'S SPECIAL</a>-->
            <li><a href="/contact">CONTACT</a></li>
            <div class="clearfix"></div>
          </ul>
          <!-- script for menu -->
          <script>
              $( "span.menu" ).click(function() {
                  $( "ul.nav1" ).slideToggle( 300, function() {
                      // Animation complete.
                  });
              });
          </script>
          <!-- //script for menu -->

        </div>
        <!-- point burst circle -->
        <div class="logo">
          <a href="index.html">
            <div class="burst-36 ">
              <div>
                <div><span><img src="/assets/logo2.png" style="width: 100%; margin-left: 6%;" alt=""/></span></div>
              </div>
            </div>
            <h1 style="margin-left: 6%;">ABOUT US</h1>
          </a>
        </div>
        <!-- //point burst circle -->


      </div>
    </div>
  </div>
</div>
<!-- //banner -->
<!-- about-page -->
<div class="about-page">
  <div class="container">
    <div class="about-info">
      <h3>ABOUT</h3>
      <div class="strip-line st-border"></div>
    </div>
    <div class="about-grids">
      <div class="col-md-7 about-grid">
        <h4>A FEW WORDS ABOUT US</h4>
        <p> Kevaldal.com (keval dal incorporation) is a online Dal shopping portal that aims to fulfilling your daily Dal requirement .</p>
        <p>No more toil walking across the market or supermarket to pick few Dals,  standing in long queues at the billing counters, stuck in traffic jam.
          Kevaldal.com ,the best and most trusted online dal store, is not only committed to save your  time , but also provides you the hand cleaned and quality Dal.</p>
        <p>
          Additionally, it delivers the products right at your doorstep within a time slot, convenient to you.
        </p>
        Purchasing Dal is now a cakewalk with Kevaldal.com
        <p>Why to purchase Dal from KEVAL DAL INC. :</p>
        <li>Open delivery</li>
        <li>No charges for delivery charges</li>
        <li>
          No question asked return policy
        </li>
        <li>
          Cash on delivery
        </li>
        <li>
          1kg is also delivered at your doorstep
        </li>
        <li>
          Manage your monthly dal requirement
        </li>
        <li>
          Multilevel quality checks before delivery
        </li>

      </div>
      <div class="col-md-5 about-grid">
        <!--<img src="/assets/g4.jpg" alt=""/>-->
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<!-- test -->
<div class="testimonial">
  <div class="container">
    <!-- responsiveslides -->

    <script>
        // You can also use "$(window).load(function() {"
        $(function () {
            // Slideshow 4
            $("#slider4").responsiveSlides({
                auto: true,
                pager: false,
                nav: false,
                speed: 500,
                namespace: "callbacks",
                before: function () {
                    $('.events').append("<li>before event fired.</li>");
                },
                after: function () {
                    $('.events').append("<li>after event fired.</li>");
                }
            });
        });
    </script>
    <!-- responsiveslides -->
    <div  id="top" class="callbacks_container">
      <ul class="rslides" id="slider4">
        <li>
          <div class="testm-info">
            <h3>KEVALDAL</h3>
            <p>
              Buy Dal online at Kevaldal.com and experience a hassle-free journey, right from payment to delivery.
            </p>
          </div>
        </li>

      </ul>
    </div>
  </div>
</div>
<!-- //test -->

<!-- //about-page -->

app/views/welcome/contact.html.erb
<!-- banner -->
<div class="banner-slider">
  <div class="banner-pos">
    <div class="banner one page-head">
      <div class="container">
        <div class="navigation text-center">
          <span class="menu"><img src="/assets/menu.png" alt=""/></span>
          <ul class="nav1">
            <li><a href="/">HOME</a></li>
            <li><a href="/about">ABOUT</a></li>
            <li><a href="/products">OUR MENU</a></li>
            <li><a href="/gallery">GALLERY</a></li>
            <!--<li><a href="typography.html">TODAY'S SPECIAL</a>-->
            <li><a class="active" href="/contact">CONTACT</a></li>
            <div class="clearfix"></div>
          </ul>
          <!-- script for menu -->
          <script>
              $( "span.menu" ).click(function() {
                  $( "ul.nav1" ).slideToggle( 300, function() {
                      // Animation complete.
                  });
              });
          </script>
          <!-- //script for menu -->

        </div>
        <!-- point burst circle -->
        <div class="logo">
          <a href="index.html">
            <div class="burst-36 ">
              <div>
                <div><span><img src="/assets/logo2.png" style="width: 100%; margin-left: 6%;" alt=""/></span></div>
              </div>
            </div>
            <h1 style="margin-left: 6%;">CONTACT</h1>
          </a>
        </div>
        <!-- //point burst circle -->


      </div>
    </div>
  </div>
</div>

<!-- //banner -->
<!-- contact-page -->
<div class="contact">
  <div class="container">
    <div class="contact-info">
      <h3>VIEW ON MAP</h3>
      <div class="strip-line"></div>
    </div>
    <div class="contact-map">
      <iframe src="https://www.google.com/maps/embed/v1/place?q=New+Arya+Nagar,+Ghaziabad,+Uttar+Pradesh,+India&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU" frameborder="0" style="border:0"></iframe>
    </div>
    <div class="contact-form">
      <div class="contact-info">
        <h3>CONTACT FORM</h3>
        <div class="strip-line"></div>
      </div>
      <form>
        <div class="contact-left">
          <input type="text" placeholder="Name" required>
          <input type="text" placeholder="E-mail" required>
          <input type="text" placeholder="Subject" required>
        </div>
        <div class="contact-right">
          <textarea placeholder="Message" required></textarea>
        </div>
        <div class="clearfix"></div>
        <input type="submit" value="SUBMIT">
      </form>
    </div>
  </div>
</div>
<!-- //contact-page -->

app/views/welcome/gallery.html.erb
<!-- banner -->
<div class="banner-slider">
  <div class="banner-pos">
    <div class="banner one page-head">
      <div class="container">
        <div class="navigation text-center">
          <span class="menu"><img src="/assets/menu.png" alt=""/></span>
          <ul class="nav1">
            <li><a href="/">HOME</a></li>
            <li><a href="/about">ABOUT</a></li>
            <li><a href="/products">OUR MENU</a></li>
            <li><a class="active" href="/gallery">GALLERY</a></li>
            <!--<li><a href="typography.html">TODAY'S SPECIAL</a>-->
            <li><a href="/contact">CONTACT</a></li>
            <div class="clearfix"></div>
          </ul>
          <!-- script for menu -->
          <script>
              $( "span.menu" ).click(function() {
                  $( "ul.nav1" ).slideToggle( 300, function() {
                      // Animation complete.
                  });
              });
          </script>
          <!-- //script for menu -->

        </div>
        <!-- point burst circle -->
        <div class="logo">
          <a href="index.html">
            <div class="burst-36 ">
              <div>
                <div><span><img src="/assets/logo2.png" style="width: 100%; margin-left: 6%;" alt=""/></span></div>
              </div>
            </div>
            <h1 style="margin-left: 6%;">Keval Dal</h1>
          </a>
        </div>
        <!-- //point burst circle -->


      </div>
    </div>
  </div>
</div>

<!-- //banner -->
<!-- gallery-page -->
<div class="gallery">
  <div class="container">
    <div class="gallery-info">
      <h3>GALLERY</h3>
      <div class="strip-line st-border"></div>
    </div>
    <div class="gallery-grids">
      <div class="col-md-4 gallery-grid gallery1">
        <a href="/assets/k1.jpg" class="swipebox"><img src="/assets/k1.jpg" class="img-responsive" alt="/">
          <div class="textbox">
          </div>
      </div></a>
      <div class="col-md-4 gallery-grid gallery1">
        <a href="/assets/k2.jpg" class="swipebox"><img src="/assets/k2.jpg" class="img-responsive" alt="/">
          <div class="textbox">
          </div>
      </div></a>
      <div class="col-md-4 gallery-grid gallery1">
        <a href="/assets/k3.jpg" class="swipebox"><img src="/assets/k3.jpg" class="img-responsive" alt="/">
          <div class="textbox">
          </div>
      </div></a>
      <div class="col-md-4 gallery-grid gallery1">
        <a href="/assets/k4.jpg" class="swipebox"><img src="/assets/k4.jpg" class="img-responsive" alt="/">
          <div class="textbox">
          </div>
      </div></a>
      <div class="col-md-4 gallery-grid gallery1">
        <a href="/assets/k5.jpg" class="swipebox"><img src="/assets/k5.jpg" class="img-responsive" alt="/">
          <div class="textbox">
          </div>
      </div></a>
      <div class="col-md-4 gallery-grid gallery1">
        <a href="assets/k6.jpg" class="swipebox"><img src="/assets/k6.jpg" class="img-responsive" alt="/">
          <div class="textbox">
          </div>
      </div></a>
      <div class="col-md-4 gallery-grid gallery1">
        <a href="/assets/k7.jpg" class="swipebox"><img src="/assets/k7.jpg" class="img-responsive" alt="/">
          <div class="textbox">
          </div>
      </div></a>
      <div class="col-md-4 gallery-grid gallery1">
        <a href="/assets/k8.jpg" class="swipebox"><img src="/assets/k8.jpg" class="img-responsive" alt="/">
          <div class="textbox">
          </div>
      </div></a>
      <div class="col-md-4 gallery-grid gallery1">
        <a href="/assets/k9.jpg" class="swipebox"><img src="/assets/k9.jpg" class="img-responsive" alt="/">
          <div class="textbox">
          </div>
      </div></a>
      <div class="clearfix"> </div>


    </div>

    <script type="text/javascript">
        jQuery(function($) {
            $(".swipebox").swipebox();
        });
    </script>
  </div>
</div>
<!-- //gallery-page -->

app/views/welcome/index.html.erb
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->


<!-- //header -->
<!-- banner -->
<div class="banner-slider">
  <div class="banner-pos">
    <!-- responsiveslides -->

    <script>
        // You can also use "$(window).load(function() {"
        $(function () {
            // Slideshow 4
            $("#slider3").responsiveSlides({
                auto: true,
                pager: false,
                nav: false,
                speed: 500,
                namespace: "callbacks",
                before: function () {
                    $('.events').append("<li>before event fired.</li>");
                },
                after: function () {
                    $('.events').append("<li>after event fired.</li>");
                }
            });
        });
    </script>
    <!-- responsiveslides -->
    <div  id="top" class="callbacks_container">
      <ul class="rslides" id="slider3">
        <li>
          <div class="banner one">
            <div class="container">
              <div class="navigation text-center">
                <span class="menu"><img src="/assets/menu.png" alt=""/></span>
                <ul class="nav1">
                  <li><a class="active" href="/">HOME</a></li>
                  <li><a href="/about">ABOUT</a></li>
                  <li><%= link_to 'OUR MENU', products_path %></li>
                  <li><a href="/gallery">GALLERY</a></li>
                  <!--<li><a href="typography.html">TODAY'S SPECIAL</a>-->
                  <li><a href="/contact">CONTACT</a></li>
                  <div class="clearfix"></div>
                </ul>
              </div>
              <!-- point burst circle -->
              <div class="logo">
                <a href="index.html">
                  <div class="burst-36 ">
                    <div>
                      <div><span><img src="/assets/logo2.png" style="width: 100%; margin-left: 6%;" alt=""/></span></div>
                    </div>
                  </div>
                  <h1 style="margin-left: 6%; width: 100%;">Keval&nbsp;Dal</h1>
                </a>
              </div>
              <!-- //point burst circle -->

              <div class="banner-info text-center">
                <p style="color: #204056">दाल चाहिए, हमे बताइए !!</p>
                <div class="order"><a href="/products">ORDER US NOW</a></div>
              </div>
            </div>
          </div>
        </li>
        <li>
          <div class="banner two">
            <div class="container">
              <div class="navigation text-center">
                <span class="menu"><img src="/assets/menu.png" alt=""/></span>
                <ul class="nav1">
                  <li><a class="active" href="/">HOME</a></li>
                  <li><a href="/about">ABOUT</a></li>
                  <li><a href="/products">OUR MENU</a></li>
                  <li><a href="/gallery">GALLERY</a></li>
                  <!--<li><a href="typography.html">TODAY'S SPECIAL</a>-->
                  <li><a href="/contact">CONTACT</a></li>
                  <div class="clearfix"></div>
                </ul>
                <!-- script for menu -->
                <script>
                    $( "span.menu" ).click(function() {
                        $( "ul.nav1" ).slideToggle( 300, function() {
                            // Animation complete.
                        });
                    });
                </script>
                <!-- //script for menu -->
              </div>
              <!-- point burst circle -->
              <div class="logo">
                <a href="/">
                  <div class="burst-36 ">
                    <div>
                      <div><span><img src="/assets/logo2.png" style="width: 100%; margin-left: 6%;" alt=""/></span></div>
                    </div>
                  </div>
                  <h1 style="margin-left: 6%; width: 100%;">Keval&nbsp;Dal</h1>
                </a>
              </div>
              <!-- //point burst circle -->

              <div class="banner-info text-center">
                <p style="color: #204056">दाल चाहिए, हमे बताइए !!</p>
                <div class="order"><a href="/products">ORDER US NOW</a></div>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
  <div class="clearfix"></div>
  <!-- banner-bottom -->
  <div class="banner-bottom">
    <div class="container">
      <div class="bottom-grids">
        <div class="col-md-4 bottom-grid text-center">
          <div class="btm-clr">
            <figure class="icon">
              <img src="/assets/k22.png" alt="" style="width: 50%;" />

            </figure>
            <h3>Fresh Dal</h3>
            <p> We present you the fresh pulses brought to you from the famous production places. try it once</p>
          </div>
        </div>
        <div class="col-md-4 bottom-grid btm-gre text-center">
          <div class="btm-clr">
            <figure class="icon">
              <img src="/assets/k11.png" alt="" style="width: 50%;" />
            </figure>
            <h3>Cheapest</h3>
            <p> You cannot find the cheaper pulses anywhere except here. we give you pulses at the cheapest rate from the market</p>
          </div>
        </div>
        <div class="col-md-4 bottom-grid text-center">
          <div class="btm-clr">
            <figure class="icon">
              <img src="/assets/k33.png" alt="" style="width: 50%;" />
            </figure>
            <h3>Special Offer</h3>
            <p> Order in Bulk and get the best price and discounts, hurry offer expires very soon. Conditions Apply</p>
          </div>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
  <!-- //banner-bottom -->
</div>
<!-- //banner -->
<!-- welcome -->
<div class="welcome">
  <div class="container">
    <div class="wel-info">
      <h3>WELCOME</h3>
      <div class="strip-line"></div>
      <p>Find the great quality of dal in our store. We promise you the best in quality and the lowest price
      </p>

    </div>
    <div class="welcome-grids">
      <div class="col-md-4 welcome-grid-img">
        <img src="/assets/pic10.jpg" alt=""/>
        <div class="wel-pos">
          <h4>Saabut Moong</h4>
        </div>
      </div>
      <div class="col-md-4 welcome-grid">
        <div class="welcome-gd second">
          <h4>Dal Fact </h4>
          <p>
            Dal protein contents are 3.5 times that of rice & 2.5 times that of egg. <br>
            By weight, cooked(boiled) Dal contains 9% protein, 70 % water, 20% carbohydrates(includes 8% fibre, 1% fat)
          </p>
        </div>
      </div>
      <div class="col-md-4 welcome-grid-img">
        <img src="/assets/picdal11.jpg" alt=""/>
        <div class="wel-pos">
          <h4>Various Options </h4>
        </div>
      </div>
      <div class="col-md-4 welcome-grid">
        <div class="welcome-gd second">
          <h4>Dal Fact</h4>
          <p>The word 'Dal' is derived from sanskrit verbal root dhal which means to "SPLIT"
          </p>
        </div>
      </div>
      <div class="col-md-4 welcome-grid-img">
        <img src="/assets/k8.jpg" alt=""/>
        <div class="wel-pos">
          <h4>High Quality</h4>
        </div>
      </div>
      <div class="col-md-4 welcome-grid">
        <div class="welcome-gd second">
          <h4>Dal Fact </h4>
          <p>The word Dal is also used to name the thick stew prepared from pulses. <br>
            Stew is a combination of solid food ingredients that have been cooked in liquid and served
            in the resultant gravy
          </p>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<!-- //welcome -->
<!-- good -->
<div class="good">
  <div class="container">
    <div class="good-info">
      <h3>WHY CHOOSE US</h3>
      <div class="strip-line"></div>
    </div>
    <div class="good-grids">
      <div class="col-md-5 good-right">
        <img src="/assets/pic12.jpg" alt=""/>
        <div class="desc">
          <p>DESERT</p>
        </div>
      </div>
      <div class="col-md-7 good-left">
        <h3>BETTER TASTING DAL</h3>
        <p>In the increasing demand of the good taste we provide you the best taste dal.</p>
        <div class="strip"></div>
        <h3>FAST, FREE DELIVERS ON ORDERS</h3>
        <p>In the increasing demand of the good taste we provide you the best taste dal.</p>
        <div class="strip"></div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<!-- //good -->
<div class="delicious">
  <div class="container">
    <div class="delicious-info">
      <h3>DELICIOUS DAL FOR ALL TASTES</h3>
      <div class="strip-line"></div>
    </div>
    <!-- delicious --><% @product_variants.each_with_index do |variant| %>
        <div class="delicious-grids" style="margin-top: -2%;">
          <div class="col-md-3 col-xs-12 col-sm-12 delicious-grid" style="margin-left: 3%; margin-top: 5%;">
            <h3><%= variant.name %></h3>
            <%= image_tag variant.variant_photos[0].variant_image %>
            <h3>Rs. <%= variant.price %>/kg</h3>


            <p style="overflow-y: auto;"><strong>Details : </strong><%= variant.description %></p>
            <!-- Button trigger modal -->

                <a class="hvr-shutter-in-horizontal button text-center" href="#" data-toggle="modal" data-target="#myModal-<%= variant.id %>" style="width: 100%;"> ADD TO CART</a>

            <%#= link_to 'ADD TO CART', add_to_cart_cart_path(:variant_id => variant.id), method: :post, :class => 'hvr-shutter-in-horizontal button', :style => 'margin-left: 24%;' %>
          </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="myModal-<%= variant.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content" >
              <div class="modal-header" style="background: #e9732f;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #fff;"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title" id="myModalLabel" style="color: #fff;">Please Select Your Quantity</h3>
              </div>


              <div class="reg">
                <%= form_tag add_to_cart_cart_path(variant.id), :method => :post do  %>
                    <div class="modal-body">
                      <input type="hidden" name="cart_item[cart_id]" value="<%= current_user.cart.id if user_signed_in? %>">
                      <input type="hidden" name="cart_item[variant_id]" value="<%= variant.id %>">
                      <h4>Type your Quantity(in Kg):</h4></br>
                      <input type="text" name="cart_item[quantity]" placeholder="Please enter number only" >

                    </div>
                    <div class="modal-footer">
                      <!--<button type="button" class="hvr-shutter-in-horizontal button" data-dismiss="modal">Close</button>-->
                      <!--<input type="button" value="CLOSE">-->
                      <input type="submit" value="ADD TO CART">
                      <!--<button type="submit" class="btn btn-primary">ADD TO CART</button>-->
                    </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>

    <% end %>
  </div>
</div>
<!-- //delicious -->

<!-- smooth scrolling -->
<script type="text/javascript">
    $(document).ready(function() {
        /*
         var defaults = {
         containerID: 'toTop', // fading element id
         containerHoverID: 'toTopHover', // fading element hover id
         scrollSpeed: 1200,
         easingType: 'linear'
         };
         */
        $().UItoTop({ easingType: 'easeOutQuart' });
    });
</script>
<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- //smooth scrolling -->

app/views/welcome/order_completed.erb
<style>
    html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,dl,dt,dd,ol,nav ul,nav li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;}
    article, aside, details, figcaption, figure,footer, header, hgroup, menu, nav, section {display: block;}
    ol,ul{list-style:none;margin:0;padding:0;}
    blockquote,q{quotes:none;}
    blockquote:before,blockquote:after,q:before,q:after{content:'';content:none;}
    table{border-collapse:collapse;border-spacing:0;}
    /* start editing from here */
    a{text-decoration:none;}
    .txt-rt{text-align:right;}/* text align right */
    .txt-lt{text-align:left;}/* text align left */
    .txt-center{text-align:center;}/* text align center */
    .float-rt{float:right;}/* float right */
    .float-lt{float:left;}/* float left */
    .clear{clear:both;}/* clear float */
    .pos-relative{position:relative;}/* Position Relative */
    .pos-absolute{position:absolute;}/* Position Absolute */
    .vertical-base{	vertical-align:baseline;}/* vertical align baseline */
    .vertical-top{	vertical-align:top;}/* vertical align top */
    .underline{	padding-bottom:5px;	border-bottom: 1px solid #eee; margin:0 0 20px 0;}/* Add 5px bottom padding and a underline */
    nav.vertical ul li{	display:block;}/* vertical menu */
    nav.horizontal ul li{	display: inline-block;}/* horizontal menu */
    img{max-width:100%;}
    /*end reset*/
    body{
        font-family:Arial, Helvetica, sans-serif;
        background:url(../assets/bg2.png);
    }
    .main{
        text-align:center;
        background: rgba(255, 255, 255, 0.04);
        color:#FFF;
        font-weight:bold;
        margin-top:160px;
        border:1px solid rgba(102, 102, 102, 0.31);
        -webkit-border-radius:5px;
        -moz-border-radius:5px;
        border-radius:5px;
    }
    .main h3{
        font-size:16px;
        text-align:left;
        padding:30px 30px;
    }
    .main h1{
        font-size:60px;
        margin-top:15px;
        color:#e9732f;
        text-transform:uppercase;
        font-family: 'Fenix', serif;
    }
    .main p{
        font-size:20px;
        margin-top:15px;
        line-height:1.6em;
    }
    .main  span.error{
        color:#e9732f;
        font-size:18px;
    }
    .main p span{
        font-size:14px;
        color:#e9732f;
    }
    .search{
        border: 1px solid rgba(173, 173, 173, 0);
        margin-left:320px;
        margin-top:20px;
        width:390px;
        position:relative;
        background:rgba(156, 156, 156, 0.12);
        box-shadow: inset 0px -1px 5px rgba(94, 94, 94, 0.19);
        border-radius:5px;
        -webkit-border-radius:5px;
        -moz-border-radius:5px;
    }
    form input[type="text"]{
        border:none;
        outline:none;
        width:289px;
        padding:8px;
        font-size:12px;
        background:rgba(255, 255, 255, 0);
        color:#A2A2A2;
    }
    form input[type="submit"]{
        border:none;
        background:none;
        cursor:pointer;
        padding:10px 20px;
        font-size:13px;
        color:#EEE;
        box-shadow: inset 1px -2px 8px rgba(0, 0, 0, 0.33);
        margin: 0;
        border-top-right-radius: 5px;
        border-bottom-right-radius: 5px;
        background:#174242;
    }
    form input[type="submit"]:hover{
        box-shadow: inset 0px 0px 4px #222;
        color:#FFF;
    }
    .icons{
        padding-bottom:20px;
        text-align:right;
    }
    .icons p{
        padding-right:130px;
        color:#D5CECE;
        font-size:13px;
        cursor:pointer;
    }
    .icons p:hover{
        text-decoration:underline;
    }
    .icons ul{
        padding-right:20px;
    }
    .icons li {
        display:inline-block;
        padding-top:10px;
    }
    .icons li a{
        margin:2px;
    }
</style>
<div class="row">
<div class="wrap col-md-6 col-lg-6 col-sm-8 col-xs-12 col-md-offset-3 col-lg-offset-3 col-sm-offset-2">
  <div class="main">
    <h3>KevalDal</h3>
    <h1>Thank You</h1>
    <p>Your Dal order has been successfully completed Please wait, Our team will call you very shortly.<br>
      <span>Don't waste your time enjoying the look of it</span></p>
    <div class="search">

    </div>
    <div class="icons">
      <p>Follow us on:</p>
      <ul>
        <li><a href="https://www.facebook.com/kevaldal12/"><img src="/assets/timg1.png"></a></li>
        <li><a href="#"><img src="/assets/timg2.png"></a></li>
      </ul>
    </div>
  </div>

</div>
</div>