config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'gallery' => 'welcome#gallery'
  get 'order_completed' => 'welcome#order_completed'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}

  resources :products
  resources :variants
  resources :carts do
    member do
      post :add_to_cart
      put :update_cart
      delete :delete_cart_item
      post :place_order
    end
  end

  resources :billings

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :variants
  has_many :cart_items
  accepts_nested_attributes_for :cart_items

  scope :active_cart, -> { where(order_completed: false) }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_filter :cart_total, only: [:place_order]

  def show
 @cart_items = CartItem.where(cart_id: current_user.cart.id, is_active: true)

  end

  def add_to_cart
    params[:cart_item][:cart_id] = current_user.cart.id
    cart_item_present = CartItem.where(cart_id: current_user.cart.id, variant_id: params[:cart_item][:variant_id], is_active: true)
    quantity  = params[:cart_item][:quantity].to_i

    if quantity != 0 && (quantity.is_a? Integer)
      p 'integer'


      if cart_item_present.present?
        flash[:error] = 'The item is already present in your cart'
        respond_to do |format|
          format.js {render js: "window.location = '#{product_path(params[:id])}';"}
        end
        return false
      end
      @cart_item = CartItem.create(cart_params)
      if @cart_item.save
        respond_to do |format|
        format.js {render js: "window.location = '#{cart_path(current_user.cart)}';"}
        end
      end
    else
      respond_to do |format|
        format.js
      end
    end
  end

  def update_cart
    @cart_items = CartItem.where(cart_id: params[:id])
    update_cart_params.keys.each do |cart_item_id|
      cart_item = @cart_items.find(cart_item_id)
      if cart_item
        cart_item.update(update_cart_params[cart_item_id])
      end
    end
    redirect_to cart_path(current_user.cart)
  end

  def delete_cart_item
   @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_path(current_user.cart)
  end

  def place_order
    p params

    @cart = Cart.where(user_id: current_user.id).first
    @cart_items = CartItem.where(cart_id: @cart.id, is_active: true)
    p  @cart_total
    CartMailer.place_order_admin_mail(@cart_items, current_user, @cart_total, current_user.billings[0], params[:order][:schedule_date], params[:order][:schedule_time]).deliver
    @previous_cart = PreviousCart.new(:user_id => current_user.id, :total => @cart_total)
    if @previous_cart.save
      @order = Order.new(order_params)
      @order.save
      @cart_items = CartItem.where(cart_id: current_user.cart.id)
      @cart_items.each do |cart_item|
        cart_item.update_attributes(:is_active => false, :previous_cart_id => @previous_cart.id)
      end
      CartMailer.place_order_mail(current_user).deliver
      flash[:notice] = 'Thank You for Placing the order. Our team will call you in a while'
      redirect_to order_completed_path
    end
  end

  private

  def cart_params
    params.require(:cart_item).permit(:quantity, :cart_id, :variant_id)
  end

  def update_cart_params
    params.require(:cart_items).permit!
  end
  def order_params
    params.require(:order).permit(:schedule_date, :schedule_time, :user_id)
  end

  def cart_total
    @cart_items = CartItem.where(cart_id: current_user.cart.id, is_active: true)
    p 'sdsddsdssdsdsdds'
    p @cart_items
    @cart_total = 0
    @cart_items.each do |cart_item|
        p 'inside'
        @cart_total += (cart_item.variant.price * cart_item.quantity)
    end
   p @cart_total
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def variant_price(variant_id)
    @variant = Variant.where(id: variant_id).first
    return @variant.price
  end
end

app/views/carts/add_to_cart.js.erb
$.toaster('Quantity should be atleast 1 Kg and in number', 'Error', 'danger');

app/views/carts/show.html.erb
<style>
        /*
        Max width before this PARTICULAR table gets nasty
        This query will take effect for any screen smaller than 760px
        and also iPads specifically.
        */
    @media
    only screen and (max-width: 760px),
    (min-device-width: 768px) and (max-device-width: 1024px)  {

        /* Force table to not be like tables anymore */
        table, thead, tbody, th, td, tr {
            display: block;
        }

        /* Hide table headers (but not display: none;, for accessibility) */
        thead tr {
            position: absolute;
            top: -9999px;
            left: -9999px;
        }

        tr { border: 1px solid #ccc; }

        td {
            /* Behave  like a "row" */
            border: none;
            border-bottom: 1px solid #eee;
            position: relative;
            padding-left: 50%;
        }

        td:before {
            /* Now like a table header */
            position: absolute;
            /* Top/left values mimic padding */
            top: 15px;
            left: 6px;
            width: 45%;
            padding-right: 71px;
            white-space: nowrap;
        }

        /*
        Label the data
        */

        td:nth-of-type(2):before { content: "Product"; }
        td:nth-of-type(3):before { content: "Price"; }
        td:nth-of-type(4):before { content: "Quantity(in Kg)"; }
        td:nth-of-type(5):before { content: "Total"; }
        td:nth-of-type(6):before { content: "Action"; }



    }

    /* Smartphones (portrait and landscape) ----------- */
    @media only screen
    and (min-device-width : 320px)
    and (max-device-width : 480px) {
        body {
            padding: 0;
            margin: 0;
             }

    }

    /* iPads (portrait and landscape) ----------- */
    @media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
        body {
            width: 495px;
        }
    }
</style>

<div class="banner-slider">
  <div class="banner-pos">
    <div class="banner one page-head" style="min-height: 200px !important;">
      <div class="container">
        <div class="navigation text-center">
          <span class="menu"><img src="/assets/menu.png" alt=""/></span>
          <ul class="nav1">
            <li><a href="/">HOME</a></li>
            <li><a href="/about">ABOUT</a></li>
            <li><a class="active" href="/products">OUR MENU</a></li>
            <li><a href="/gallery">GALLERY</a></li>
            <!--<li><a href="typography.html">TODAY'S SPECIAL</a>-->
            <li><a href="/contact">CONTACT</a></li>
            <div class="clearfix"></div>
          </ul>
          <!-- script for menu -->
          <script>
              $( "span.menu" ).click(function() {
                  $( "ul.nav1" ).slideToggle( 300, function() {
                      // Animation complete.
                  });
              });
          </script>
          <!-- //script for menu -->

        </div>
        <!-- point burst circle -->
        <div class="title ">
          <div class="logo">
            <a href="index.html">
              <h1 style="font-size: 50px;">ORDERS</h1>
            </a>
          </div>

        </div>
        <!-- //point burst circle -->
      </div>
    </div>
  </div>
</div>


<div class="cart">
  <div class="row">
<section id="cart-view">
<div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="cart-view-area">
          <div class="cart-view-table">

              <div class="">
                <table class="table">
                  <thead>
                  <tr>

                    <th></th>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity(in Kg)</th>
                    <th>Total</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>

                  <%= form_tag update_cart_cart_path, method: "PUT"  do |f| %>
                  <% @cart_items.each do |cart_item| %>
                  <tr class="items">

                    <td><%= image_tag cart_item.variant.variant_photos[0].variant_image, :style => 'width: 100px; height:100px' %></td>
                    <td><a class="aa-cart-title" href="#"><%= cart_item.variant.name %></a></td>
                    <td>Rs. <%= cart_item.variant.price %>/kg</td>
                    <td><%= fields_for "cart_items[#{cart_item.id}]" do |p| %>


                          <input type="number" name="cart_items[<%= cart_item.id %>][quantity]" id="cart_items_<%= cart_item.id %>_quantity" rel="<%= cart_item.variant.price %>" value="<%= cart_item.quantity %>" class="aa-cart-quantity product-quantity">
                          <% end %></td>

                    <td>Rs. <%= (cart_item.variant.price) * (cart_item.quantity) %></td>
                    <td><%= link_to 'Delete Item', delete_cart_item_cart_path(cart_item.id), :method => :delete, :confirm => "Are you sure?", :class => 'hvr-shutter-in-horizontal button' %></td>
                  </tr>
                    <% end %>

                    <td colspan="8" class="aa-cart-view-bottom">
                      <div class="reg">

                      <input type="submit" value="UPDATE CART" class="hvr-shutter-in-horizontal button">
                      </div>
                      <%#= link_to 'Update Cart', '#', :class => 'hvr-shutter-in-horizontal button' %>

                    </td>
                  </tr>
                      <% end %>

                  </tbody>
                </table>
                <!-- Cart Total view -->
                <div class="cart-view-total" style="width: 100% !important;">
                  <h4>Cart Totals</h4>
                  <table class="aa-totals-table col-lg-12">
                    <tbody>
                    <tr>
                      <th>Subtotal</th>
                      <td>Rs. <%= cart_total %></td>
                    </tr>
                    <tr>
                      <th>Total</th>
                      <td>Rs. <%= cart_total %></td>
                    </tr>
                    </tbody>
                  </table>

                  <%= link_to 'Proceed to Checkout', billing_path, data: { no_turbolink: true }, :class => 'hvr-shutter-in-horizontal button' %>

                </div>
              </div>


          </div>
        </div>
      </div>
    </div>
</div>
</section>
</div>
  </div>

<script>


        $('.product-quantity').on('input', function() {
            var totalValue = ($(this).attr('rel')) * (parseFloat($(this).val()));
            $(this).closest('td').next().text('Rs.' + totalValue);
        });
//    });

</script>