config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'gallery' => 'welcome#gallery'
  get 'order_completed' => 'welcome#order_completed'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}

  resources :products
  resources :variants
  resources :carts do
    member do
      post :add_to_cart
      put :update_cart
      delete :delete_cart_item
      post :place_order
    end
  end

  resources :billings

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :variants
  belongs_to :category

  has_attached_file :product_image, :styles => { medium: "300x300>", thumb: "100x100>" },
                    :s3_protocol => :https,
                    :url => ':s3_domain_url',
                    :path => '/product_image/:id/:style_:basename.:extension'

  validates_attachment_content_type :product_image, content_type: /\Aimage\/.*\Z/
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
   @product = Product.new
    @categories = Category.all
  end

    def edit
      @product = Product.where(id: params[:id]).first
      @categories = Category.all
      p @product
    end

    def update
      @product = Product.where(id: params[:id]).first

      if @product.update_attributes(products_params)
        redirect_to products_path
      end
    end

  def create
    @product = Product.create(products_params)
    if @product.save
      flash[:success] = "Product saved"
      redirect_to products_path
    else
      flash[:error] = "Error"
      render :new
    end
  end

  def index
    @products = Product.all

  end

  def show
    @product = Product.where(id: params[:id]).first
    @product_variants = Variant.where(product_id: params[:id])

  end

  private

  def products_params
    params.require(:product).permit(:name, :description, :category_id, :product_image)
  end
end

app/views/products/edit.html.erb
<div class="registration-form">
  <div class="container">
    <h3>Create Product</h3>
    <div class="strip"></div>
    <div class="registration-grids">
      <div class="reg-form">
        <div class="reg">
          <p>Welcome, please create your product </p>

          <%= form_for @product do |f| %>
              <ul>
                <li class="text-info">Product Name: </li>
                <li><%= f.text_field :name %></li>
              </ul>
              <ul>
                <li class="text-info">Description: </li>
                <li><%= f.text_area :description, :style => 'width: 100%; height: 269px;' %></li>
              </ul>
              <ul>
                <li class="text-info">Image Upload: </li>
                <li><%= f.file_field :product_image %></li>
              </ul>
              <ul>
                <li class="text-info">Category: </li>
                <li><%= f.collection_select :category_id, @categories, :id, :name,{prompt: "Select a category"}, {class: "form-control ", } %></li>
              </ul>

              <input type="submit" value="CREATE PRODUCT">

          <% end %>
        </div>
      </div>

      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="banner-slider">
  <div class="banner-pos">
    <div class="banner one page-head">
      <div class="container">
        <div class="navigation text-center">
          <span class="menu"><img src="/assets/menu.png" alt=""/></span>
          <ul class="nav1">
            <li><a href="/">HOME</a></li>
            <li><a href="/about">ABOUT</a></li>
            <li><a class="active" href="/products">OUR MENU</a></li>
            <li><a href="/gallery">GALLERY</a></li>
            <!--<li><a href="typography.html">TODAY'S SPECIAL</a>-->
            <li><a href="/contact">CONTACT</a></li>
            <div class="clearfix"></div>
          </ul>
          <!-- script for menu -->
          <script>
              $( "span.menu" ).click(function() {
                  $( "ul.nav1" ).slideToggle( 300, function() {
                      // Animation complete.
                  });
              });
          </script>
          <!-- //script for menu -->

        </div>
        <!-- point burst circle -->
        <div class="logo">
          <a href="index.html">
            <div class="burst-36 ">
              <div>
                <div><span><img src="/assets/logo2.png" style="width: 100%; margin-left: 6%;" alt=""/></span></div>
              </div>
            </div>
            <h1>PRODUCTS</h1>
          </a>
        </div>
        <!-- //point burst circle -->

      </div>
    </div>
  </div>
</div>

<!-- //banner -->
<!-- menu-page -->
<div class="menu">
  <div class="container">
    <div class="menu-info">
      <h3>CHECK OUT OUR MENU HERE</h3>
      <% if user_signed_in? && current_user.is_admin == true %>
        <h3><%= link_to 'Create Product', new_product_path, data: { no_turbolink: true } %> </h3>
      <% end %>
      <div class="strip-line"></div>
    </div>
    <div class="our-menu-grids">
      <% unless @products.blank?%>
      <% @products.each do |product| %>
      <div class="order-top">
        <li class="im-g"><a href="#"><%= image_tag product.product_image, :class => 'img-responsive' %></li>
        <li class="data">
          <h3>
            <% if product.variants.count == 1 %>
                <%= product.variants.pluck(:price).min %> Rs
                <% else %>

            <%= product.variants.pluck(:price).min %> - <%= product.variants.pluck(:price).max %> Rs
                <% end %>
          </h3>
          <h4><%= link_to product.name, product_path(product), :style => 'color: #e9732f;' %></h4>
          <p><%= raw(product.description) %></p>
        </li>
            <li class="bt-nn">
              <%= link_to 'EXPLORE', product_path(product), :class => 'hvr-shutter-in-horizontal button' %>
            </li>
        <div class="clearfix"></div>
      </div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>
<!-- //menu-page -->

app/views/products/new.html.erb
<script>

        $('.ckeditor').ckeditor({
            // optional config

        });

</script>
<div class="registration-form">
  <div class="container">
    <h3>Create Product</h3>
    <div class="strip"></div>
    <div class="registration-grids">
      <div class="reg-form">
        <div class="reg">
          <p>Welcome, please create your product </p>

          <%= form_for @product do |f| %>
            <ul>
              <li class="text-info">Product Name: </li>
              <li><%= f.text_field :name %></li>
            </ul>
            <ul>
              <li class="text-info">Description: </li>
               <%= f.text_area :description, :class => 'ckeditor' %>
              <%#= f.text_area :description, :style => 'width: 100%; height: 269px;' %>
            </ul>
              <ul>
                <li class="text-info">Image Upload: </li>
                <li><%= f.file_field :product_image %></li>
              </ul>
            <ul>
              <li class="text-info">Category: </li>
              <li><%= f.collection_select :category_id, @categories, :id, :name,{prompt: "Select a category"}, {class: "form-control ", } %></li>
            </ul>

            <input type="submit" value="CREATE PRODUCT">

          <% end %>
        </div>
      </div>

      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="banner-slider">
  <div class="banner-pos">
    <div class="banner one page-head">
      <div class="container">
        <div class="navigation text-center">
          <span class="menu"><img src="/assets/menu.png" alt=""/></span>
          <ul class="nav1">
            <li><a href="/">HOME</a></li>
            <li><a href="/about">ABOUT</a></li>
            <li><a class="active" href="/products">OUR MENU</a></li>
            <li><a href="/gallery">GALLERY</a></li>
            <!--<li><a href="typography.html">TODAY'S SPECIAL</a>-->
            <li><a href="/contact">CONTACT</a></li>
            <div class="clearfix"></div>
          </ul>
          <!-- script for menu -->
          <script>
              $( "span.menu" ).click(function() {
                  $( "ul.nav1" ).slideToggle( 300, function() {
                      // Animation complete.
                  });
              });
          </script>
          <!-- //script for menu -->

        </div>
        <!-- point burst circle -->
        <div class="logo">
          <a href="index.html">
            <div class="burst-36 ">
              <div>
                <div><span><img src="/assets/logo2.png" style="width: 100%; margin-left: 6%;" alt=""/></span></div>
              </div>
            </div>
            <h1>PRODUCTS</h1>
          </a>
        </div>
        <!-- //point burst circle -->

      </div>
    </div>
  </div>
</div>


<div class="delicious">
  <div class="container">
    <div class="delicious-info">
      <h3>CHOOSE YOUR DAL </h3>
      <div class="strip-line"></div>
      <% if user_signed_in? && current_user.is_admin == true %>
        <h3><%= link_to 'Create Variant', new_variant_path(:product_id => @product.id) %></h3>
      <% end %>
    </div>



        <% @product_variants.each_with_index do |variant| %>
          <div class="delicious-grids" style="margin-top: -2%;">
            <div class="col-md-3 col-xs-12 col-sm-6 delicious-grid" style="margin-left: 3%; margin-top: 5%;">
              <h3><%= variant.name %></h3>
              <% if user_signed_in? && current_user.is_admin == true %>
                  <h3><%= link_to 'edit', edit_variant_path(variant) %></h3>
              <% end %>
              <%= image_tag variant.variant_photos[0].variant_image %>
              <h3>Rs. <%= variant.price %>/kg</h3>


              <p style="overflow-y: auto;"><strong>Details : </strong><%= variant.description %></p>
              <!-- Button trigger modal -->
             <% if user_signed_in? %>
                <a class="hvr-shutter-in-horizontal button text-center" href="#" data-toggle="modal" data-target="#myModal-<%= variant.id %>" style="width: 100%;"> ADD TO CART</a>
             <% else %>
                <%= link_to 'ADD TO CART', new_user_session_path, :class=> 'hvr-shutter-in-horizontal button text-center', :style => 'width: 100%;' %>
             <% end %>
                <%#= link_to 'ADD TO CART', add_to_cart_cart_path(:variant_id => variant.id), method: :post, :class => 'hvr-shutter-in-horizontal button', :style => 'margin-left: 24%;' %>
            </div>
          </div>
        <!-- Modal -->
        <div class="modal fade" id="myModal-<%= variant.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content" >
              <div class="modal-header" style="background: #e9732f;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #fff;"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title" id="myModalLabel" style="color: #fff;">Please Select Your Quantity</h3>
              </div>


                  <div class="reg">
              <%= form_tag add_to_cart_cart_path, :method => :post, :remote => true do  %>
              <div class="modal-body">
               <input type="hidden" name="cart_item[cart_id]" value="<%= current_user.cart.id if user_signed_in? %>">
                <input type="hidden" name="cart_item[variant_id]" value="<%= variant.id %>">
                <h4>Type your Quantity(in Kg):</h4></br>
                <input type="text" name="cart_item[quantity]" placeholder="Please enter number only" >

              </div>
              <div class="modal-footer">
                <!--<button type="button" class="hvr-shutter-in-horizontal button" data-dismiss="modal">Close</button>-->
                <!--<input type="button" value="CLOSE">-->
                <input type="submit" value="ADD TO CART">
                <!--<button type="submit" class="btn btn-primary">ADD TO CART</button>-->
              </div>
              <% end %>
                    </div>
            </div>
          </div>
        </div>

        <% end %>

  </div>
</div>
<div class="about-page">
  <div class="container">
    <div class="about-info">
      <h3><%= @product.name %></h3>
      <% if user_signed_in? && current_user.is_admin == true %>
          <h3><%= link_to 'edit', edit_product_path(@product) %></h3>
      <% end %>

      <div class="strip-line st-border"></div>
    </div>
    <div class="about-grids">
      <div class="col-md-7 about-grid">
        <h4>A FEW WORDS ABOUT THE PRODUCT</h4>
        <p> <%= raw(@product.description) %></p>

      </div>
      <div class="col-md-5 about-grid">
        <%= image_tag @product.product_image %>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>